version: "3.0"
services:
  bank-backend:
    container_name: bank-backend
    command: yarn dev
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - "./src:/usr/src/app/src"
    links:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:11
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
